server:
  port: 9091
spring :
  datasource :
    url: "jdbc:postgresql://localhost:5432/apgs"  
    username: postgres  
    password: admin
  jpa:
    properties :
      hibernate :
        default_schema : apgss
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto : update
